### ISSUE TITLE
Error wile running the project locally

### ISSUE THREAD

**Issue by omar-dulaimi** [Progyan1997/fastapi-example#2]
Hey,

I'm a python noob, faced this error and not sure if I'm missing a dependency or the project.
Here's the message: 

`ModuleNotFoundError: No module named 'configs.Environment'`

**Comment by omar-dulaimi** [comment]
Turns out that `Environment` should be `environment` like this: 
```python
configs.environment
```

Two places to change:

1- Line `#5` in `main.py`
2- Line `#4` in `configs/Database.py`

**Comment by Progyan1997** [comment]
Great to know that. Just curious, are you happen to be running inside Windows machine?

**Comment by omar-dulaimi** [comment]
No, not really. I'm using Ubuntu.

**Comment by Progyan1997** [comment]
@omar-dulaimi My apologies, turns out the file was mistakenly renamed from commit and/or push. Fixed it now!

**Comment by omar-dulaimi** [comment]
Awesome, great I could help!
